env:
  browser: true
  node: true
  commonjs: true
  mocha: true
globals:
  expect: true
extends: airbnb
parser: babel-eslint
parserOptions:
  ecmaVersion: 7
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
    modules: true
plugins:
- react
rules:
  indent:
  - error
  - tab
  -
    SwitchCase: 1
    MemberExpression: 1
  quotes:
  - error
  - single
  - allowTemplateLiterals: true
  object-curly-spacing:
  - error
  - always
  - arraysInObjects: false
  template-curly-spacing:
  - error
  - always
  comma-dangle: 'off'
  no-tabs: 'off'
  no-unused-vars: 'warn'
  no-console: 'off'
  no-undef: 'warn'
  no-empty-patterns: 'off'
  anchor-has-content: 'off'
  linebreak-style: 'off'
  no-useless-constructor: 'off'
  no-use-before-define: 'off'
  no-empty-pattern: 'off'
  consistent-return: 'off'
  class-methods-use-this: 'off'
  arrow-body-style: 'off'
  no-underscore-dangle: 'off'
  array-callback-return: 'off'
  global-require: 'off'
  no-trailing-spaces: 'off'
  spaced-comment: 'off'
  no-shadow: 'off'
  eol-last: 'off'
  one-var: 'off'
  arrow-parens: 'off'
  no-param-reassign: 'off'
  brace-style: 'off'
  no-case-declarations: 'off'
  import/first: 'off'
  import/no-unresolved: 'off'
  import/extensions: 'off'
  import/no-extraneous-dependencies: 'off'
  import/prefer-default-export: 'off'
  import/no-dynamic-require: 'off'
  react/sort-comp: 'off'
  react/prefer-stateless-function: 'off'
  react/prop-types: 'warn'
  react/jsx-indent: 'off'
  react/jsx-indent-props: 'off'
  react/jsx-curly-spacing: 'off'
  react/jsx-filename-extension: 'off'
  react/no-danger: 'off'
  react/forbid-prop-types: 'off'
  react/self-closing-comp: 'off'
  react/jsx-space-before-closing: 'off'
  react/no-unused-prop-types: 'warn'
  react/no-did-mount-set-state: 'off'
  jsx-a11y/img-has-alt: 'off'
  jsx-a11y/no-static-element-interactions: 'off'
